# Generated by Django 4.1 on 2023-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booker'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='booker',
        ),
        migrations.AddField(
            model_name='tile',
            name='img',
            field=models.ImageField(default=1, height_field=15, max_length=20, upload_to='', width_field=15),
            preserve_default=False,
        ),
    ]
